name: verify
on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:

     - name: checkout
       uses: actions/checkout@v5
       with:
         fetch-depth: 1

     - name: setup
       uses: actions/setup-go@v6
       with:
         go-version: "1.25"

     - name: vet
       run: go vet ./...

     - name: fmt
       run: |
         files=$(gofmt -s -l .)
         if [ -n "$files" ]; then
           echo "badly formatted files"
           echo "$files"
           exit 1
         fi

     - name: test
       run: go test ./...
